/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainPanel.java
 *
 * Created on 9 sept. 2011, 18:21:19
 */
package draganddrop.panel;

import draganddrop.panel.classes.Bateau;
import draganddrop.panel.classes.TableModeListBateau;
import draganddrop.panel.classes.TableModelBateau;
import draganddrop.panel.classes.TransferHandlerBateau;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DropMode;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.TransferHandler;

/**
 *
 * @author Nabot
 */
public class MainPanel extends javax.swing.JPanel
{

  /** Creates new form MainPanel */
  public MainPanel()
  {
    initComponents();
    postInitComponents();
  }

  private void postInitComponents()
  {
    List<Bateau> bateaux = new ArrayList<>();
    Bateau bateau = new Bateau("Rogger", 78, "Katamarant");
    bateaux.add(bateau);
    bateau = new Bateau("Bob", 77, "Katadrole");
    bateaux.add(bateau);
    bateau = new Bateau("René", 88, "Péniche");
    bateaux.add(bateau);
    bateau = new Bateau("Toto", 8, "Sousmarrin");
    bateaux.add(bateau);
    bateau = new Bateau("Louise", 58, "Surmarrant");
    bateaux.add(bateau);
    bateau = new Bateau("Gontrand", 26, "Navire");
    bateaux.add(bateau);

    TableModeListBateau tableModeListBateau = new TableModeListBateau(bateaux);
    jTableSource.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    jTableSource.setModel(tableModeListBateau);
    jTableSource.setTransferHandler(new TransferHandlerBateau());

    bateaux = new ArrayList<>();
    bateau = new Bateau("", -1, "");
    bateaux.add(bateau);
    TableModelBateau tableModeBateau = new TableModelBateau(bateaux);
    jTableDest.setModel(tableModeBateau);
    jTableDest.setDropMode(DropMode.INSERT);
    jTableDest.setTransferHandler(new TransferHandlerBateau());
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneDest = new javax.swing.JScrollPane();
        jTableDest = new javax.swing.JTable();
        jScrollPaneSource = new javax.swing.JScrollPane();
        jTableSource = new javax.swing.JTable();

        setName("Form"); // NOI18N

        jScrollPaneDest.setName("jScrollPaneDest"); // NOI18N

        jTableDest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDest.setName("jTableDest"); // NOI18N
        jScrollPaneDest.setViewportView(jTableDest);

        jScrollPaneSource.setName("jScrollPaneSource"); // NOI18N

        jTableSource.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSource.setName("jTableSource"); // NOI18N
        jTableSource.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTableSourceMouseDragged(evt);
            }
        });
        jScrollPaneSource.setViewportView(jTableSource);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPaneDest, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneSource, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneDest, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
            .addComponent(jScrollPaneSource, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

  private void jTableSourceMouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTableSourceMouseDragged
  {//GEN-HEADEREND:event_jTableSourceMouseDragged
    JTable comp = (JTable) evt.getSource();
    TransferHandler handler = comp.getTransferHandler();
    handler.exportAsDrag(comp, evt, TransferHandler.COPY);
    evt.consume();
  }//GEN-LAST:event_jTableSourceMouseDragged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPaneDest;
    private javax.swing.JScrollPane jScrollPaneSource;
    private javax.swing.JTable jTableDest;
    private javax.swing.JTable jTableSource;
    // End of variables declaration//GEN-END:variables
}
